# -*- coding: utf-8 -*-
"""pa1_uwm_compsci202_sp21_rr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qb0x9QgXrlTY3DQM9EFvOoAUWBaE3ZJi
"""

#programming assignment 2
# Compose a program to determine the length of a ladder
# required to reach a specified height when leaned against a house.

import math

def ladderlength():
  h = float(input("How high do you need the ladder to reach (ft)? "))
  a = float(input("At what angle will the ladder be leaning against your house (degrees)? "))
  length = round((h/math.sin((math.pi/180)*a)),3)
  print()
  print("You'll need to use or purchase a ladder that is", math.ceil(length), "feet or greater,") 
  print("then adjust your ladder to", length, "feet to reach a height of", h, "feet.")

ladderlength()